name: Deploy Frontend to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            # Variables
            REPO_URL="https://github.com/YOUR-USERNAME/YOUR-REPO.git"
            APP_DIR="/home/ubuntu/activity-frontend"
            SERVICE_FILE="/etc/systemd/system/activity-frontend.service"

            # Clone or pull latest
            if [ ! -d "$APP_DIR/.git" ]; then
              git clone $REPO_URL $APP_DIR
            else
              cd $APP_DIR
              git pull origin main
            fi

            cd $APP_DIR

            # Install Node and serve if not present
            if ! command -v node >/dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            sudo npm install -g serve

            # Install dependencies and build
            npm install
            npm run build

            # Create systemd service file
            sudo bash -c "cat > $SERVICE_FILE" <<EOF
            [Unit]
            Description=Activity Suggestion Frontend (React) Service
            After=network.target

            [Service]
            Type=simple
            User=ubuntu
            WorkingDirectory=$APP_DIR
            ExecStart=$(which serve) -s dist -l 3000
            Restart=always
            Environment=NODE_ENV=production

            [Install]
            WantedBy=multi-user.target
            EOF

            # Reload and restart service
            sudo systemctl daemon-reload
            sudo systemctl enable activity-frontend
            sudo systemctl restart activity-frontend